---
title: "Practica_programada1"
author: "Joseline Portuguez L"
date: "2023-07-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(readxl)
library(tidyr)
library(janitor) 
library(lubridate)
library(hms)
```

A.

```{r}
datos_netflix_info <-read_csv2("https://raw.githubusercontent.com/isa229/programacion_analisis_datos_ii/main/netflix_info.csv")
```

B. Ajuste los nombres de las columnas para que estén en español.

```{r}
datos_netflix_info <- datos_netflix_info |> 
  rename("ID"="show_id","Tipo"="type","Titulo"="title","Director"="director","Pais"="country","Fecha_agregacion"="date_added","Año_lanzamiento"="release_year","Clasificacion"="rating","Duracion"="duration","Categoria"="listed_in")
```

C. Elimine filas duplicadas.

```{r}
datos_netflix_info <- datos_netflix_info |> 
distinct()
```

```{r}
filas_duplicadas <- datos_netflix_info |>  
  janitor::get_dupes()
```

D. Eliminar filas y columnas vacías.

```{r}
datos_netflix_info <- datos_netflix_info|> 
  remove_empty(which = c("rows", "cols"))
```

E. Elimine la variable correspondiente al año de lanzamiento (release_year.)

```{r}
datos_netflix_info <- select(datos_netflix_info, -Año_lanzamiento)
```